sudo: required
services:
        - docker

before_install:
        - docker build -t goodkit/docker-react -f Dockerfile.dev .

script:
        - docker run goodkit/docker-react npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: "eu-west-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-eu-west-2-791428552910"
        bucket_path: "docker-react"
        on:
                branch: master
        acces_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
